// One-off: strip obvious junk (function words + very short words) from the
// already-generated German file, without re-translating. Run: node scripts/clean-de.mjs
import { readFileSync, writeFileSync } from 'node:fs';

import { STOP } from './de-stopwords.mjs';

const FILE = new URL('../src/data/words-de.generated.ts', import.meta.url);
const text = readFileSync(FILE, 'utf8');

// Pull the JSON string out of `JSON.parse("…")`, then parse it to the array.
const m = text.match(/JSON\.parse\(\s*("(?:[^"\\]|\\.)*")/s);
if (!m) {
  console.error('could not find JSON.parse payload');
  process.exit(1);
}
const words = JSON.parse(JSON.parse(m[1]));

const before = words.length;
const kept = words.filter((w) => {
  const h = String(w.headword).toLowerCase();
  return h.length >= 3 && !STOP.has(h);
});

const out =
  `// AUTO-GENERATED by scripts/build-words-de.mjs — do not edit by hand.\n` +
  `// German vocabulary from the hermitdave FrequencyWords list (MIT),\n` +
  `// bucketed by frequency; Russian via MyMemory, examples via Tatoeba.\n` +
  `import type { Word } from '@/types/domain';\n\n` +
  `// Stored as a JSON string parsed at load (avoids the TS2590 union blow-up).\n` +
  `export const GENERATED_DE: Word[] = JSON.parse(\n  ${JSON.stringify(JSON.stringify(kept))},\n);\n`;
writeFileSync(FILE, out);
console.log(`filtered German ${before} -> ${kept.length} (removed ${before - kept.length})`);
